// apps/cms/src/pages/CalendarSources.tsx
import { useEffect, useMemo, useState } from "react";
import { adminApi } from "../lib/api";

interface CalendarSourceRow {
  id: string;
  title: string;
  type: string;
  ownerId: string;
  status: string;
  classLabel?: string;
  currentVersionNo?: number;
  versionCount: number;
  eventCount: number;
  subscriptionCount: number;
  updatedAt: string;
}

export function CalendarSources() {
  const [items, setItems] = useState<CalendarSourceRow[]>([]);
  const [selectedSourceId, setSelectedSourceId] = useState("");
  const [versions, setVersions] = useState<Array<{ id: string; versionNo: number; status: string; createdBy: string; createdAt: string; publishedAt?: string }>>([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const totals = useMemo(() => ({
    events: items.reduce((sum, item) => sum + item.eventCount, 0),
    subscriptions: items.reduce((sum, item) => sum + item.subscriptionCount, 0),
  }), [items]);

  const load = async () => {
    setLoading(true);
    setError("");
    try {
      const data = await adminApi.get<{ items: CalendarSourceRow[] }>("calendar/sources");
      setItems(data.items || []);
    } catch (err) {
      setError(err instanceof Error ? err.message : "加载失败");
    } finally {
      setLoading(false);
    }
  };

  const showVersions = async (sourceId: string) => {
    setLoading(true);
    setError("");
    try {
      const data = await adminApi.get<{ versions: Array<{ id: string; versionNo: number; status: string; createdBy: string; createdAt: string; publishedAt?: string }> }>(`calendar/sources/${encodeURIComponent(sourceId)}`);
      setSelectedSourceId(sourceId);
      setVersions(data.versions || []);
    } catch (err) {
      setError(err instanceof Error ? err.message : "加载版本失败");
    } finally {
      setLoading(false);
    }
  };

  const publishVersion = async (versionNo: number) => {
    if (!selectedSourceId) return;
    setLoading(true);
    setError("");
    try {
      await adminApi.publishCalendarSourceVersion(selectedSourceId, versionNo);
      await load();
      await showVersions(selectedSourceId);
    } catch (err) {
      setError(err instanceof Error ? err.message : "发布失败");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { void load(); }, []);

  return (
    <section className="card">
      <div className="card-head">
        <div><h2>日程源</h2><p>GET /api/v1/calendar/sources · 旧 Schedule 兼容映射。</p></div>
        <button className="button ghost" onClick={load}>{loading ? "加载中..." : "刷新"}</button>
      </div>
      <div className="actions" style={{ marginBottom: 12 }}>
        <span className="pill">Sources {items.length}</span>
        <span className="pill">Events {totals.events}</span>
        <span className="pill">Subscriptions {totals.subscriptions}</span>
      </div>
      {error ? <p className="muted">{error}</p> : null}
      <div className="table-wrap">
        <table>
          <thead><tr><th>标题</th><th>类型</th><th>归属</th><th>状态</th><th>版本</th><th>事件</th><th>订阅</th><th>操作</th></tr></thead>
          <tbody>
            {items.map((item) => (
              <tr key={item.id}>
                <td><strong>{item.title}</strong><div className="muted">{item.id}</div></td>
                <td><span className="pill">{item.type}</span></td>
                <td>{item.classLabel || item.ownerId}</td>
                <td>{item.status}</td>
                <td>v{item.currentVersionNo || 0} / {item.versionCount}</td>
                <td>{item.eventCount}</td>
                <td>{item.subscriptionCount}</td>
                <td><button className="button ghost" onClick={() => void showVersions(item.id)}>版本</button></td>
              </tr>
            ))}
            {items.length === 0 ? <tr><td colSpan={8} className="muted">暂无数据或未登录</td></tr> : null}
          </tbody>
        </table>
      </div>
      {selectedSourceId ? <><h2 style={{ marginTop: 18 }}>版本列表</h2><p className="muted">{selectedSourceId}</p><div className="table-wrap"><table><thead><tr><th>版本</th><th>状态</th><th>创建人</th><th>时间</th><th>操作</th></tr></thead><tbody>
        {versions.map((version) => <tr key={version.id}><td><strong>v{version.versionNo}</strong><div className="muted">{version.id}</div></td><td><span className="pill">{version.status}</span></td><td>{version.createdBy || "-"}</td><td>{version.publishedAt || version.createdAt}</td><td><button className="button ghost" disabled={loading || version.status === "published"} onClick={() => void publishVersion(version.versionNo)}>发布</button></td></tr>)}
        {versions.length === 0 ? <tr><td colSpan={5} className="muted">暂无版本</td></tr> : null}
      </tbody></table></div></> : null}
    </section>
  );
}

// apps/backend/app/pages/nexus/calendar-sources.vue
<template>
  <NexusAdminShell title="Calendar Sources" @refresh="loadData">
    <section class="rx-grid">
      <article class="rx-card">
        <span class="rx-pill">Sources</span>
        <h2>{{ sources.length }}</h2>
        <p>由旧 Schedule 兼容映射出的通用日程源。</p>
      </article>
      <article class="rx-card">
        <span class="rx-pill">Published Events</span>
        <h2>{{ eventCount }}</h2>
        <p>当前发布版本下的源事件数量。</p>
      </article>
      <article class="rx-card">
        <span class="rx-pill">Subscriptions</span>
        <h2>{{ subscriptionCount }}</h2>
        <p>基于 CalendarSubscription 的新 API 视角。</p>
      </article>
      <article class="rx-card">
        <span class="rx-pill">Admin</span>
        <h2>shadcn</h2>
        <p>新后台页面不再写入旧 NexusConsole。</p>
      </article>
    </section>

    <section class="rx-card">
      <header class="rx-card-head">
        <div>
          <h2>日程源列表</h2>
          <p>CalendarSource / Version / Event 兼容层已接入。</p>
        </div>
        <button class="rx-btn rx-btn-ghost" type="button" :disabled="loading" @click="loadData">
          {{ loading ? "加载中..." : "刷新" }}
        </button>
      </header>

      <p v-if="errorText" class="rx-muted">{{ errorText }}</p>
      <div class="rx-table-wrap">
        <table class="rx-table">
          <thead>
            <tr>
              <th>标题</th>
              <th>类型</th>
              <th>归属</th>
              <th>状态</th>
              <th>版本</th>
              <th>事件</th>
              <th>订阅</th>
              <th>更新时间</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in sources" :key="item.id">
              <td>
                <strong>{{ item.title }}</strong>
                <div class="rx-muted">{{ item.id }}</div>
              </td>
              <td><span class="rx-pill">{{ item.type }}</span></td>
              <td>{{ item.classLabel || item.ownerId }}</td>
              <td>{{ item.status }}</td>
              <td>v{{ item.currentVersionNo || 0 }} / {{ item.versionCount }}</td>
              <td>{{ item.eventCount }}</td>
              <td>{{ item.subscriptionCount }}</td>
              <td>{{ toDisplayDate(item.updatedAt) }}</td>
              <td><button class="rx-btn rx-btn-ghost" type="button" @click="showVersions(item.id)">版本</button></td>
            </tr>
            <tr v-if="sources.length === 0">
              <td colspan="9" class="rx-muted">暂无日程源</td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>

    <section class="rx-card" v-if="selectedSourceId">
      <header class="rx-card-head">
        <div>
          <h2>版本列表</h2>
          <p>{{ selectedSourceId }}</p>
        </div>
      </header>
      <div class="rx-table-wrap">
        <table class="rx-table">
          <thead><tr><th>版本</th><th>状态</th><th>创建人</th><th>发布时间</th><th>操作</th></tr></thead>
          <tbody>
            <tr v-for="version in versions" :key="version.id">
              <td><strong>v{{ version.versionNo }}</strong><div class="rx-muted">{{ version.id }}</div></td>
              <td><span class="rx-pill">{{ version.status }}</span></td>
              <td>{{ version.createdBy || '-' }}</td>
              <td>{{ toDisplayDate(version.publishedAt || version.createdAt) }}</td>
              <td><button class="rx-btn rx-btn-ghost" type="button" :disabled="loading || version.status === 'published'" @click="publishVersion(version.versionNo)">发布</button></td>
            </tr>
            <tr v-if="versions.length === 0"><td colspan="5" class="rx-muted">暂无版本</td></tr>
          </tbody>
        </table>
      </div>
    </section>
  </NexusAdminShell>
</template>

<script setup lang="ts">
import NexusAdminShell from "../../components/nexus/NexusAdminShell.vue";
import { useNexusApi } from "../../composables/nexus/useNexusApi";

interface CalendarSourceRow {
  id: string;
  title: string;
  type: string;
  ownerId: string;
  status: string;
  classLabel?: string;
  currentVersionNo?: number;
  versionCount: number;
  eventCount: number;
  subscriptionCount: number;
  updatedAt: string;
}

const { ensureSessionToken, request, goToLogin } = useNexusApi();
const loading = ref(false);
const errorText = ref("");
const sources = ref<CalendarSourceRow[]>([]);
const selectedSourceId = ref("");
const versions = ref<any[]>([]);

const eventCount = computed(() => sources.value.reduce((sum, item) => sum + Number(item.eventCount || 0), 0));
const subscriptionCount = computed(() => sources.value.reduce((sum, item) => sum + Number(item.subscriptionCount || 0), 0));

const toDisplayDate = (value: unknown) => {
  const parsed = Date.parse(String(value || ""));
  if (!Number.isFinite(parsed)) {
    return String(value || "");
  }
  return new Date(parsed).toLocaleString("zh-CN");
};

const showVersions = async (sourceId: string) => {
  selectedSourceId.value = sourceId;
  loading.value = true;
  errorText.value = "";
  try {
    const data = await request<{ versions: any[] }>(`/api/v1/calendar/sources/${encodeURIComponent(sourceId)}`);
    versions.value = data.versions || [];
  } catch (error) {
    errorText.value = error instanceof Error ? error.message : "加载版本失败";
  } finally {
    loading.value = false;
  }
};

const publishVersion = async (versionNo: number) => {
  if (!selectedSourceId.value) return;
  loading.value = true;
  errorText.value = "";
  try {
    await request(`/api/v1/admin/calendar/sources/${encodeURIComponent(selectedSourceId.value)}/versions/${versionNo}/publish`, { method: "POST", body: {} });
    await loadData();
    await showVersions(selectedSourceId.value);
  } catch (error) {
    errorText.value = error instanceof Error ? error.message : "发布失败";
  } finally {
    loading.value = false;
  }
};

const loadData = async () => {
  loading.value = true;
  errorText.value = "";
  try {
    const data = await request<{ items: CalendarSourceRow[] }>("/api/v1/calendar/sources");
    sources.value = data.items || [];
  } catch (error) {
    errorText.value = error instanceof Error ? error.message : "加载失败";
  } finally {
    loading.value = false;
  }
};

onMounted(async () => {
  if (!ensureSessionToken()) {
    await goToLogin();
    return;
  }
  await loadData();
});
</script>
