// apps/cms/src/pages/NotificationChannels.tsx
import { useEffect, useState } from "react";
import { adminApi } from "../lib/api";

type ChannelType = "wechat_clawdbot" | "feishu";

interface ChannelRow {
  id: string;
  type: ChannelType;
  name: string;
  enabled: boolean;
  config: Record<string, string>;
}

export function NotificationChannels() {
  const [items, setItems] = useState<ChannelRow[]>([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const load = async () => {
    setLoading(true);
    setError("");
    try {
      const data = await adminApi.listNotificationChannels() as unknown as { items: ChannelRow[] };
      setItems(data.items || []);
    } catch (err) {
      setError(err instanceof Error ? err.message : "加载失败");
    } finally {
      setLoading(false);
    }
  };
  const toggle = async (item: ChannelRow) => {
    await adminApi.upsertNotificationChannel({ type: item.type, name: item.name, enabled: !item.enabled });
    await load();
  };
  const sendTest = async (type: ChannelType) => {
    await adminApi.testNotificationChannel(type);
    await load();
  };
  const dispatchPending = async () => {
    await adminApi.dispatchPendingNotificationDeliveries(20);
    await load();
  };
  useEffect(() => { void load(); }, []);
  return (
    <section className="card">
      <div className="card-head"><div><h2>通知通道</h2><p>ClawDBot + 飞书模型已进入 API 与 notification-core。</p></div><div className="actions"><button className="button ghost" onClick={() => void dispatchPending()}>投递 pending</button><button className="button ghost" onClick={load}>{loading ? "加载中..." : "刷新"}</button></div></div>
      {error ? <p className="muted">{error}</p> : null}
      <div className="table-wrap">
        <table>
          <thead><tr><th>通道</th><th>类型</th><th>状态</th><th>配置</th><th>操作</th></tr></thead>
          <tbody>
            {items.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.type}</td><td><span className="pill">{item.enabled ? "已启用" : "未启用"}</span></td><td className="muted">{Object.keys(item.config || {}).filter((key) => item.config[key]).join(" / ") || "未配置"}</td><td><button className="button ghost" onClick={() => void toggle(item)}>{item.enabled ? "停用" : "启用"}</button><button className="button ghost" onClick={() => void sendTest(item.type)}>测试</button></td></tr>)}
            {items.length === 0 ? <tr><td colSpan={5} className="muted">暂无数据或未登录</td></tr> : null}
          </tbody>
        </table>
      </div>
    </section>
  );
}

// apps/backend/app/pages/nexus/notification-channels.vue
<template>
  <NexusReactShell title="Notification Channels" @refresh="loadData">
    <section class="rx-card">
      <header class="rx-card-head">
        <div>
          <h2>通知通道重构</h2>
          <p>目标通道：微信 ClawDBot + 飞书。已接入 NotificationChannel 数据模型与测试投递记录。</p>
        </div>
        <div>
          <button class="rx-btn rx-btn-ghost" type="button" :disabled="loading" @click="dispatchPending">投递 pending</button>
          <button class="rx-btn rx-btn-ghost" type="button" :disabled="loading" @click="loadData">
            {{ loading ? "加载中..." : "刷新" }}
          </button>
        </div>
      </header>
      <p v-if="errorText" class="rx-muted">{{ errorText }}</p>
      <div class="rx-table-wrap">
        <table class="rx-table">
          <thead>
            <tr>
              <th>通道</th>
              <th>类型</th>
              <th>状态</th>
              <th>配置摘要</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in channels" :key="item.id">
              <td>{{ item.name }}</td>
              <td><span class="rx-pill">{{ item.type }}</span></td>
              <td>{{ item.enabled ? "已启用" : "未启用" }}</td>
              <td class="rx-muted">{{ formatConfig(item.config) }}</td>
              <td>
                <button class="rx-btn rx-btn-ghost" type="button" :disabled="loading" @click="toggleChannel(item)">
                  {{ item.enabled ? "停用" : "启用" }}
                </button>
                <button class="rx-btn rx-btn-ghost" type="button" :disabled="loading" @click="sendTest(item.type)">测试</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>

    <section class="rx-card">
      <header class="rx-card-head">
        <div>
          <h2>最近测试投递</h2>
          <p>当前测试发送先写入 NotificationDelivery，后续接真实 adapter。</p>
        </div>
      </header>
      <div class="rx-table-wrap">
        <table class="rx-table">
          <thead>
            <tr><th>标题</th><th>通道</th><th>状态</th><th>时间</th><th>错误</th></tr>
          </thead>
          <tbody>
            <tr v-for="item in deliveries" :key="item.id">
              <td>{{ item.title }}</td>
              <td>{{ item.channelType }}</td>
              <td>{{ item.status }}</td>
              <td>{{ toDisplayDate(item.createdAt) }}</td>
              <td class="rx-muted">{{ item.errorMessage || "-" }}</td>
            </tr>
            <tr v-if="deliveries.length <= 0"><td colspan="5" class="rx-muted">暂无投递记录</td></tr>
          </tbody>
        </table>
      </div>
    </section>
  </NexusReactShell>
</template>

<script setup lang="ts">
import NexusReactShell from "../../components/nexus/NexusReactShell.vue";
import { useNexusApi } from "../../composables/nexus/useNexusApi";

type ChannelType = "wechat_clawdbot" | "feishu";

interface ChannelRow {
  id: string;
  type: ChannelType;
  name: string;
  enabled: boolean;
  config: Record<string, string>;
}

interface DeliveryRow {
  id: string;
  channelType: ChannelType;
  title: string;
  status: string;
  createdAt: string;
  errorMessage?: string;
}

const { ensureSessionToken, request, goToLogin } = useNexusApi();
const loading = ref(false);
const errorText = ref("");
const channels = ref<ChannelRow[]>([]);
const deliveries = ref<DeliveryRow[]>([]);

const formatConfig = (config: Record<string, string>) => {
  const active = Object.entries(config || {}).filter(([, value]) => String(value || "").trim());
  return active.length > 0 ? active.map(([key, value]) => `${key}: ${value}`).join(" / ") : "未配置密钥";
};

const toDisplayDate = (value: unknown) => {
  const parsed = Date.parse(String(value || ""));
  return Number.isFinite(parsed) ? new Date(parsed).toLocaleString("zh-CN") : String(value || "");
};

const loadData = async () => {
  loading.value = true;
  errorText.value = "";
  try {
    const [channelData, deliveryData] = await Promise.all([
      request<{ items: ChannelRow[] }>("/api/v1/admin/notification-channels"),
      request<{ items: DeliveryRow[] }>("/api/v1/admin/notification-deliveries?limit=20"),
    ]);
    channels.value = channelData.items || [];
    deliveries.value = deliveryData.items || [];
  } catch (error) {
    errorText.value = error instanceof Error ? error.message : "加载失败";
  } finally {
    loading.value = false;
  }
};

const toggleChannel = async (item: ChannelRow) => {
  loading.value = true;
  errorText.value = "";
  try {
    await request("/api/v1/admin/notification-channels", {
      method: "POST",
      body: {
        type: item.type,
        name: item.name,
        enabled: !item.enabled,
      },
    });
    await loadData();
  } catch (error) {
    errorText.value = error instanceof Error ? error.message : "保存失败";
  } finally {
    loading.value = false;
  }
};

const dispatchPending = async () => {
  loading.value = true;
  errorText.value = "";
  try {
    await request("/api/v1/admin/notification-deliveries/dispatch-pending", {
      method: "POST",
      body: { limit: 20 },
    });
    await loadData();
  } catch (error) {
    errorText.value = error instanceof Error ? error.message : "投递失败";
  } finally {
    loading.value = false;
  }
};

const sendTest = async (type: ChannelType) => {
  loading.value = true;
  errorText.value = "";
  try {
    await request(`/api/v1/admin/notification-channels/${encodeURIComponent(type)}/test`, {
      method: "POST",
      body: {},
    });
    await loadData();
  } catch (error) {
    errorText.value = error instanceof Error ? error.message : "测试失败";
  } finally {
    loading.value = false;
  }
};

onMounted(async () => {
  if (!ensureSessionToken()) {
    await goToLogin();
    return;
  }
  await loadData();
});
</script>
