// apps/backend/app/pages/nexus/notification-deliveries.vue
<template>
  <NexusReactShell title="Notification Deliveries" @refresh="loadData">
    <section class="rx-card">
      <header class="rx-card-head">
        <div>
          <h2>投递记录</h2>
          <p>查看 NotificationDelivery 状态、重试次数、外部消息 ID 与失败原因。</p>
        </div>
        <div>
          <button class="rx-btn rx-btn-ghost" type="button" :disabled="loading" @click="dispatchPending">投递 pending</button>
          <button class="rx-btn rx-btn-ghost" type="button" :disabled="loading" @click="loadData">
            {{ loading ? "加载中..." : "刷新" }}
          </button>
        </div>
      </header>
      <p v-if="errorText" class="rx-muted">{{ errorText }}</p>
      <div class="rx-table-wrap">
        <table class="rx-table">
          <thead>
            <tr>
              <th>标题</th>
              <th>用户</th>
              <th>通道</th>
              <th>状态</th>
              <th>计划时间</th>
              <th>重试</th>
              <th>外部 ID</th>
              <th>错误</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in deliveries" :key="item.id">
              <td><strong>{{ item.title }}</strong><div class="rx-muted">{{ item.templateKey }}</div></td>
              <td>{{ item.userId }}</td>
              <td><span class="rx-pill">{{ item.channelType }}</span></td>
              <td>{{ item.status }}</td>
              <td>{{ toDisplayDate(item.scheduledAt || item.createdAt) }}</td>
              <td>{{ item.attemptCount || 0 }}</td>
              <td class="rx-muted">{{ item.externalMessageId || "-" }}</td>
              <td class="rx-muted">{{ item.errorMessage || "-" }}</td>
            </tr>
            <tr v-if="deliveries.length <= 0"><td colspan="8" class="rx-muted">暂无投递记录</td></tr>
          </tbody>
        </table>
      </div>
    </section>
  </NexusReactShell>
</template>

<script setup lang="ts">
import NexusReactShell from "../../components/nexus/NexusReactShell.vue";
import { useNexusApi } from "../../composables/nexus/useNexusApi";

interface DeliveryRow {
  id: string;
  userId: string;
  channelType: string;
  templateKey: string;
  title: string;
  status: string;
  scheduledAt: string;
  createdAt: string;
  attemptCount: number;
  externalMessageId?: string;
  errorMessage?: string;
}

const { ensureSessionToken, request, goToLogin } = useNexusApi();
const loading = ref(false);
const errorText = ref("");
const deliveries = ref<DeliveryRow[]>([]);

const toDisplayDate = (value: unknown) => {
  const parsed = Date.parse(String(value || ""));
  return Number.isFinite(parsed) ? new Date(parsed).toLocaleString("zh-CN") : String(value || "");
};

const loadData = async () => {
  loading.value = true;
  errorText.value = "";
  try {
    const data = await request<{ items: DeliveryRow[] }>("/api/v1/admin/notification-deliveries?limit=80");
    deliveries.value = data.items || [];
  } catch (error) {
    errorText.value = error instanceof Error ? error.message : "加载失败";
  } finally {
    loading.value = false;
  }
};

const dispatchPending = async () => {
  loading.value = true;
  errorText.value = "";
  try {
    await request("/api/v1/admin/notification-deliveries/dispatch-pending", {
      method: "POST",
      body: { limit: 50 },
    });
    await loadData();
  } catch (error) {
    errorText.value = error instanceof Error ? error.message : "投递失败";
  } finally {
    loading.value = false;
  }
};

onMounted(async () => {
  if (!ensureSessionToken()) {
    await goToLogin();
    return;
  }
  await loadData();
});
</script>

// apps/cms/src/pages/NotificationDeliveries.tsx
import { useEffect, useState } from "react";
import { adminApi } from "../lib/api";

interface DeliveryRow {
  id: string;
  userId: string;
  channelType: string;
  templateKey: string;
  title: string;
  body: string;
  status: string;
  dedupeKey: string;
  scheduledAt: string;
  sentAt?: string;
  externalMessageId?: string;
  errorMessage?: string;
  attemptCount: number;
  createdAt: string;
  updatedAt: string;
}

export function NotificationDeliveries() {
  const [items, setItems] = useState<DeliveryRow[]>([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const load = async () => {
    setLoading(true);
    setError("");
    try {
      const data = await adminApi.listNotificationDeliveries({ limit: 50 }) as { items: DeliveryRow[] };
      setItems(data.items || []);
    } catch (err) {
      setError(err instanceof Error ? err.message : "加载失败");
    } finally {
      setLoading(false);
    }
  };

  const dispatchPending = async () => {
    setLoading(true);
    setError("");
    try {
      await adminApi.dispatchPendingNotificationDeliveries(50);
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : "投递失败");
      setLoading(false);
    }
  };

  useEffect(() => { void load(); }, []);

  return (
    <section className="card">
      <div className="card-head">
        <div>
          <h2>投递记录</h2>
          <p>NotificationDelivery 入队、发送、失败与外部回执。</p>
        </div>
        <div className="actions">
          <button className="button ghost" onClick={() => void dispatchPending()}>投递 pending</button>
          <button className="button ghost" onClick={load}>{loading ? "加载中..." : "刷新"}</button>
        </div>
      </div>
      {error ? <p className="muted">{error}</p> : null}
      <div className="table-wrap">
        <table>
          <thead>
            <tr>
              <th>消息</th>
              <th>通道</th>
              <th>状态</th>
              <th>计划/发送</th>
              <th>重试</th>
              <th>外部结果</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item) => (
              <tr key={item.id}>
                <td>
                  <strong>{item.title}</strong>
                  <div className="muted">{item.body}</div>
                  <div className="muted">{item.dedupeKey}</div>
                </td>
                <td>{item.channelType}<div className="muted">{item.templateKey}</div></td>
                <td><span className="pill">{item.status}</span></td>
                <td>{item.scheduledAt}<div className="muted">{item.sentAt || "未发送"}</div></td>
                <td>{item.attemptCount}</td>
                <td className="muted">{item.errorMessage || item.externalMessageId || "-"}</td>
              </tr>
            ))}
            {items.length === 0 ? <tr><td colSpan={6} className="muted">暂无投递记录</td></tr> : null}
          </tbody>
        </table>
      </div>
    </section>
  );
}
